InternShipProject/urls.py
from django.contrib import admin
from django.urls import path, re_path, reverse_lazy
from billingManager import views, models, reporting
from django.views.generic import UpdateView, DeleteView, ListView, DetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create_service/', views.create_service, name='create_service'),
    path('create_district/', views.create_district, name='create_district'),
    path('create_town/', views.create_town, name='create_town'),
    path('create_provider/', views.create_provider, name='create_provider'),
    path('create_bill/', views.create_bill, name='create_bill'),
    path('create_tva/', views.create_tva, name='create_tva'),
    path('create_rr/', views.create_rr, name='create_r_r'),
    #path('add_user/', views.add_user, name='add_user'),
    path('connexion/', views.connexion, name='connexion'),
    path('logout/', views.logout_page, name='logout'),

    # Order Office

    path('bill_consulting_opened', views.view_bill_opened, name='bill_consulting_opened'),

    path('bill_consulting_rejected_BO', views.view_bill_rejected_bo, name='bill_consulting_rejected_BO'),

    path('bill_consulting_closed', views.view_bill_closed, name='bill_consulting_closed'),

    path('bill_detail/<pk>', DetailView.as_view(model=models.Bill, template_name='billDetail.html', ),
         name='bill_detail'),

    path('bill_treatment/<pk>', views.bill_treatment, name='bill_treatment'),

    path('BO_treatment/<pk>', views.bo_treatment, name='BO_treatment'),

    path('slip_edit', views.slip_edit, name='slip_edit'),

    path('reporting_BO/<pk>', views.reporting_pdf, name='reporting_BO'),

    # Treating Service

    path('bill_consulting_not_treated_ST', views.view_bill_not_treated_st, name='bill_consulting_not_treated_ST'),

    path('bill_consulting_opened_ST', views.view_bill_opened_st, name='bill_consulting_opened_ST'),

    path('bill_consulting_closed_ST', views.view_bill_closed_st, name='bill_consulting_closed_ST'),


    path('bill_treatment_ST/<pk>', views.bill_treatment_st, name='bill_treatment_ST'),

    path('ST_treatment/<pk>', views.st_treatment, name='ST_treatment'),

    #####

# Financial Service

    path('bill_consulting_not_treated_FC', views.view_bill_not_treated_fc, name='bill_consulting_not_treated_FC'),

    path('bill_consulting_opened_FC', views.view_bill_opened_fc, name='bill_consulting_opened_FC'),

    path('bill_consulting_closed_FC', views.view_bill_closed_fc, name='bill_consulting_closed_FC'),

    path('bill_treatment_FC/<pk>', views.bill_treatment_fc, name='bill_treatment_FC'),

    path('FC_treatment/<pk>', views.fc_treatment, name='FC_treatment'),

    #####

    path('bill/<pk>/delete/', views.bill_delete, name='bill_delete'),

    path('bill/<pk>/update/', views.bill_update, name='bill_update'),

    path('provider_consulting', views.view_provider, name='provider_consulting'),

    path('provider_detail/<pk>', DetailView.as_view(model=models.Provider, template_name='providerDetail.html', ),
         name='provider_detail'),

    path('provider/<pk>/delete/', views.provider_delete, name='provider_delete'),

    path('provider/<pk>/update/', views.provider_update, name='provider_update'),

    path('service_consulting', views.view_service, name='service_consulting'),

    path('service/<pk>/delete/', views.service_delete, name='service_delete'),

    path('service/<pk>/update/', views.service_update, name='service_update'),

    path('town_consulting', views.view_town, name='town_consulting'),

    path('town/<pk>/delete/', views.town_delete, name='town_delete'),

    path('town/<pk>/update/', views.town_update, name='town_update'),

    path('district_consulting', ListView.as_view(model=models.District, template_name='districtConsulting.html', ),
         name='district_consulting'),

    path('district/<pk>/delete/', views.district_delete, name='district_delete'),

    path('district/<pk>/update/', views.district_update, name='district_update'),

    path('tva_consulting', views.view_tva, name='tva_consulting'),

    path('tva/<pk>/delete/', views.tva_delete, name='tva_delete'),

    path('tva/<pk>/update/', views.tva_update, name='tva_update'),

    path('district_consulting', views.view_district, name='district_consulting'),

    path('reasons_consulting', views.view_reason, name='reasons_consulting'),

    path('reason/<pk>/delete/', views.reason_delete, name='reason_delete'),

    path('reason/<pk>/update/', views.reason_update, name='reason_update'),

# Staff

    path('bill_consulting_all', views.view_all_bill, name='bill_consulting_all'),


]

billingManager/models.py

from django.db import models
from django.contrib.auth.models import User


class Service(models.Model):
    service_id = models.AutoField(primary_key=True)
    service_name = models.CharField(max_length=50, verbose_name="Designation du service")
    service_abv = models.CharField(max_length=10, verbose_name='Abreviation du service')

    def __str__(self):
        return self.service_name


class District(models.Model):
    district_id = models.AutoField(primary_key=True)
    district_designation = models.CharField(max_length=50, verbose_name="Designation du district")

    def __str__(self):
        return self.district_designation


class TVA(models.Model):
    tva_id = models.AutoField(primary_key=True)
    tva_rate = models.FloatField(verbose_name="Taux de TVA")

    def __str__(self):
        return str(self.tva_rate)


class Slip(models.Model):
    slip_id = models.AutoField(primary_key=True, verbose_name="Id du bordereau")
    slip_num = models.IntegerField(verbose_name='Numéro du bordereau')
    closed = models.BooleanField(default=False)
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service"
                                , blank=True, null=True)

    def __str__(self):
        return str(self.slip_num) + "/" + str(self.service.service_abv)


class ServiceSlip(models.Model):
    slip_id = models.AutoField(primary_key=True, verbose_name="Id du bordereau")
    slip_num = models.IntegerField(verbose_name='Numéro du bordereau')
    closed = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=1, verbose_name='Valide')

    def __str__(self):
        if self.is_valid:
            returned_val = str(self.slip_num) + "/" + 'Validation'
        else:
            returned_val = str(self.slip_num) + "/" + 'Rejet'
        return returned_val


class RejectionReason(models.Model):
    rejection_id = models.AutoField(primary_key=True)
    reason = models.CharField(max_length=100, verbose_name="Motif de rejet")

    def __str__(self):
        return self.reason


class Town(models.Model):
    town_id = models.AutoField(primary_key=True)
    town_name = models.CharField(max_length=30, verbose_name="Nom de la ville")
    postal_code = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Code postal")

    def __str__(self):
        return self.town_name


class Provider(models.Model):
    GENDER = [
        ('1', 'Madame'),
        ('2', 'Monsieur'),
        ('3', 'Mademoiselle'),
    ]

    provider_id = models.AutoField(primary_key=True)
    gender = models.CharField(max_length=1, choices=GENDER, default='2', verbose_name="Genre")
    provider_last_name = models.CharField(max_length=50, verbose_name="Nom")
    provider_first_name = models.CharField(max_length=50, verbose_name="Prénom")
    provider_address = models.CharField(max_length=150, verbose_name="Addrese")
    town = models.ForeignKey(Town, on_delete=models.PROTECT, verbose_name="Ville")
    email = models.EmailField()
    fixed_phone = models.CharField(max_length=9, verbose_name="Téléphone fix")
    mobile_phone = models.CharField(max_length=10, verbose_name="Téléphone mobile")
    rib = models.CharField(max_length=20, verbose_name="RIB")
    nif = models.CharField(max_length=20, verbose_name="NIF")
    r_commerce = models.CharField(max_length=20, verbose_name="raison Comercial")

    def __str__(self):
        return self.provider_last_name.upper() + " " + self.provider_first_name.capitalize()


class Bill(models.Model):
    DECISION = [
        ('1', 'Non Traiter'),
        ('2', 'Accepter'),
        ('3', 'Refuser'),
    ]

    bill_id = models.AutoField(primary_key=True)
    bill_num = models.CharField(max_length=50, verbose_name="Numéro de facture")
    entry_date = models.DateField(auto_now=True)
    object = models.TextField(max_length=150, verbose_name="Objet")
    bill_type = models.CharField(max_length=100, verbose_name="Type de facture", blank=True)
    decision_ST = models.CharField(max_length=1, choices=DECISION, default='1')
    decision_BO = models.CharField(max_length=1, choices=DECISION, default='1')
    penalty_rate = models.FloatField(default=0, verbose_name="taux de pénalité")
    ht_amount = models.FloatField(verbose_name='Montant HT')
    other_coasts = models.FloatField(default=0, verbose_name="Autres frais")
    decision_FC = models.CharField(max_length=1, choices=DECISION, default='1')
    transfer_order = models.CharField(max_length=20, blank=True, verbose_name="Ordre de virement")
    billing_date = models.DateField(verbose_name="Date de facturation")
    provider = models.ForeignKey(Provider, on_delete=models.PROTECT, verbose_name="Fournisseur")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service")
    district = models.ForeignKey(District, on_delete=models.PROTECT, verbose_name="District")
    tva = models.ForeignKey(TVA, on_delete=models.PROTECT, verbose_name="Taux de TVA")
    slip = models.ForeignKey(Slip, on_delete=models.PROTECT, null=True, verbose_name="Numéro du bordereau")
    service_slip = models.ForeignKey(ServiceSlip, on_delete=models.PROTECT, null=True, verbose_name="Numéro du bordereau de service traitant")
    rejection_reasonBO = models.ManyToManyField(RejectionReason, related_name='motif1')
    rejection_reasonST = models.ManyToManyField(RejectionReason, related_name='motif2')
    rejection_reasonFC = models.ManyToManyField(RejectionReason, related_name='motif3')
    entered_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name='Saisie par')

    def __str__(self):
        return self.bill_num

    class Meta:
        ordering = ('-entry_date',)


class UserProfile(models.Model):
    user_auth = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    mobile_phone = models.CharField(max_length=9, blank=True, verbose_name='Téléphone portable')
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service", null=True)
    service_all = models.BooleanField(default=False)
    district = models.ForeignKey(District, on_delete=models.PROTECT, verbose_name="District", null=True)
    district_all = models.BooleanField(default=False)
    born_date = models.DateField(verbose_name="Date de naissance", blank=True)
    years_seniority = models.IntegerField(verbose_name="Années d'ancienneté", blank=True)

    def __str__(self):
        return self.user_auth.last_name.upper() + " " + self.user_auth.first_name.capitalize()



billingManager/forms.py
from django.contrib.auth import authenticate
from billingManager import models
from django import forms
from .models import Bill, Provider, Service, Town, District, TVA, RejectionReason


class BillForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = (
            'bill_num', 'provider', 'object', 'bill_type', 'penalty_rate', 'ht_amount', 'other_coasts', 'billing_date',
            'service', 'district', 'tva', 'transfer_order')


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = (
            'gender', 'provider_last_name', 'provider_first_name', 'provider_address', 'town', 'email', 'fixed_phone',
            'mobile_phone', 'rib', 'nif', 'r_commerce')


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = (
            'service_name', 'service_abv')


class TownForm(forms.ModelForm):
    class Meta:
        model = Town
        fields = (
            'town_name', 'postal_code')


class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = (
            'district_designation',)


class TVAForm(forms.ModelForm):
    class Meta:
        model = TVA
        fields = (
            'tva_rate',)


class ReasonForm(forms.ModelForm):
    class Meta:
        model = RejectionReason
        fields = (
            'reason',)


class FormCreateBill(forms.ModelForm):
    class Meta:
        model = models.Bill
        exclude = ('decision_ST', 'decision_FC', 'entry_date', 'rejection_reasonFC', 'slip', 'service_slip',
                   'rejection_reasonST', 'transfer_order', 'rejection_reasonBO', 'decision_BO', 'entered_by')


class FormCreateTown(forms.ModelForm):
    class Meta:
        model = models.Town
        fields = '__all__'


class FormCreateProvider(forms.ModelForm):
    class Meta:
        model = models.Provider
        fields = '__all__'


class FormCreateSlip(forms.ModelForm):
    class Meta:
        model = models.Slip
        fields = '__all__'


class FormCreateService(forms.ModelForm):
    class Meta:
        model = models.Service
        fields = '__all__'


class FormCreateDistrict(forms.ModelForm):
    class Meta:
        model = models.District
        fields = '__all__'


class FormCreateTVA(forms.ModelForm):
    class Meta:
        model = models.TVA
        fields = '__all__'


class FormCreateRejectionReason(forms.ModelForm):
    class Meta:
        model = models.RejectionReason
        fields = '__all__'


class FormAddUser(forms.Form):
    last_name = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50)
    login = forms.CharField(max_length=50, label="Nom d'utilisateur")
    email = forms.EmailField(label="Email")
    born_date = forms.DateField(widget=forms.DateInput)
    mobile_phone = forms.CharField(max_length=9)
    years_seniority = forms.IntegerField()
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
    password_bis = forms.CharField(label="Validation du mot de passe", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(FormAddUser, self).clean()
        password = cleaned_data.get('password')
        password_bis = self.cleaned_data.get('password_bis')
        if password and password_bis and password != password_bis:
            raise forms.ValidationError("Passwords are not identical.")
        return cleaned_data


class FormConnection(forms.Form):
    username = forms.CharField(max_length=50, label="Nom d'utilisateur")
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(FormConnection, self).clean()

        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Wrong login or password")
        return cleaned_data


class FormSlipEdit(forms.ModelForm):
    class Meta:
        model = models.Slip
        fields = ('service',)


class FormBillTreatment(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonBO', )


class FormBillTreatmentST(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonST', )


class FormBillTreatmentFC(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonFC', )

billingManager/templates/Financial_Service/billConsultingNotTreatedFC.html
{% extends 'baseForm.html' %}
{% load static %}
{% load widget_tweaks %}
{% load poll_extras %}

{% block TitleHTML %}
Consultation des Factures
{% endblock %}

{% block the_form %}
<div class="alert top alert-success" role="alert">
  Operation effectué avec succès !
</div>
<div class="alert top alert-danger" role="alert">
    Operation a échoué car elle est lié à une autre entité !
</div>
{% load django_bootstrap_breadcrumbs %}
<div class="row">
    <div class="col-xs-6">
        <h2>Consultation des Factures</h2>
    </div>
    <div class="col-xs-6">
        {% block content %}
            {{ block.super }}
            {% breadcrumb "Consulter" "bill_consulting_not_treated_FC" %}
            {% breadcrumb "Factures non Traitées" "#" %}
        {% endblock %}
    </div>
</div>
{% if filter.qs.count != 0 %}
<div class="direct-content">
    <div class="filter-section">
        <form method="get">
           {% csrf_token %}
            {% include '../filters_section.html' %}
        </form>
    </div>
    <table class="table table-hover table-striped table-bordered" id="bill-table">
      <thead>
        <tr>
          <th scope="col">Numero</th>
          <th scope="col">Fournisseur</th>
          <th scope="col">Service</th>
          <th scope="col">District</th>
          <th scope="col">Date saisie</th>
          <th scope="col">Montant HT</th>
          <th scope="col" width="7%">Action</th>
        </tr>
      </thead>
      <tbody>
        {% include 'includes/partial_bill_list_not_treated_FC.html' %}
      </tbody>
    </table>
    {% include "pagination.html" with page=bill_filters %}
</div>
{% else %}
<div class="direct-content">
    <div class="alert alert-info" role="alert">
        Aucune facture disponible !
    </div>
</div>
{% endif %}
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-bill">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>

    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script>
    $(function () {

    /* Functions */

    var loadForm = function () {
    var btn = $(this);
    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-bill").modal("show");
      },
      success: function (data) {
        $("#modal-bill .modal-content").html(data.html_form);
      }
    });
    };

    var saveForm = function () {
    var form = $(this),
        id = $(".js-bill-update-form").data("id");
    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
          $("#bill-table tbody").html(data.html_bill_list);
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-success").slideDown(300).delay(2500).slideUp(300);
        }
        else {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
        }
      },
      error: function (XMLHttpRequest, textStatus, errorThrown) {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
     }
    });
    return false;
    };


    //Update Bill
    $("#bill-table").on("click", ".js-update-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-update-form", saveForm);

    //Delete Bill
    $("#bill-table").on("click", ".js-delete-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-delete-form", saveForm);




     $("tr").find('td').click(function(){
         if(!($(this).hasClass("not-allowed"))){

             window.location = $(this).parent("tr").data('url');
         }
     });

    });
    </script>
{% endblock %}

billingManager/templates/Financial_Service/billConsultingServiceSlipClosedFC.html
{% extends 'baseForm.html' %}
{% load static %}
{% load widget_tweaks %}
{% load poll_extras %}

{% block TitleHTML %}
Consultation des Factures
{% endblock %}

{% block the_form %}
<div class="alert top alert-success" role="alert">
  Operation effectué avec succès !
</div>
<div class="alert top alert-danger" role="alert">
    Operation a échoué car elle est lié à une autre entité !
</div>
{% load django_bootstrap_breadcrumbs %}
<div class="row">
    <div class="col-xs-6">
        <h2>Consultation des Factures</h2>
    </div>
    <div class="col-xs-6">
        {% block content %}
            {{ block.super }}
            {% breadcrumb "Consulter" "bill_consulting_closed_FC" %}
            {% breadcrumb "Factures avec OV" "#" %}
        {% endblock %}
    </div>
</div>
{% if filter.qs.count != 0 %}
<div class="direct-content">
    <div class="filter-section">
        <form method="get">
           {% csrf_token %}
            {% include '../filters_section.html' %}
        </form>
    </div>
    <table class="table table-hover table-striped table-bordered" id="bill-table">
      <thead>
        <tr>
          <th scope="col">Numero</th>
          <th scope="col">Fournisseur</th>
          <th scope="col">Service</th>
          <th scope="col">District</th>
          <th scope="col">Date saisie</th>
          <th scope="col">Montant HT</th>
          <th scope="col" width="7%">Action</th>
        </tr>
      </thead>
      <tbody>
        {% include 'includes/partial_bill_list_closed_FC.html' %}
      </tbody>
    </table>
    {% include "pagination.html" with page=bill_filters %}
</div>
{% else %}
<div class="direct-content">
    <div class="alert alert-info" role="alert">
        Aucune facture disponible !
    </div>
</div>
{% endif %}
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-bill">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>

    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script>
    $(function () {

    /* Functions */

    var loadForm = function () {
    var btn = $(this);
    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-bill").modal("show");
      },
      success: function (data) {
        $("#modal-bill .modal-content").html(data.html_form);
      }
    });
    };

    var saveForm = function () {
    var form = $(this),
        id = $(".js-bill-update-form").data("id");
    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
          $("#bill-table tbody").html(data.html_bill_list);
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-success").slideDown(300).delay(2500).slideUp(300);
        }
        else {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
        }
      },
      error: function (XMLHttpRequest, textStatus, errorThrown) {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
     }
    });
    return false;
    };


    //Update Bill
    $("#bill-table").on("click", ".js-update-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-update-form", saveForm);

    //Delete Bill
    $("#bill-table").on("click", ".js-delete-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-delete-form", saveForm);



    });
    </script>
{% endblock %}

billingManager/templates/Financial_Service/billTreatmentFC.html
{% extends 'baseForm.html' %}
{% load static %}
{% load widget_tweaks %}

{% load poll_extras %}

{% block TitleHTML %}
    Detail de la facture numéro {{ bill.bill_num }}
{% endblock %}

{% block header %}
    Detail de la facture numéro {{ bill.bill_num }}
{% endblock %}

{% block the_form %}
    {% load django_bootstrap_breadcrumbs %}
    <div class="row">
        <div class="col-xs-6">
            <h2>Detail de la Facture</h2>
        </div>
        <div class="col-xs-6">
            {% block content %}
                {{ block.super }}
                {% breadcrumb "Facture non Traitées" "bill_consulting_not_treated_FC" %}
                {% breadcrumb "Detail" "#" %}
            {% endblock %}
        </div>
    </div>
    {% include "includes/progress_bar.html" %}
    <div class="direct-content">
        <div class="bill-detail" data-id="{{ bill.bill_id }}">
            {% include 'includes/partial_bill_detail.html' %}
        </div>
        {% if bill.decision_FC == "1" %}
        <div class="actions pull-right">
            <a href="{% url 'FC_treatment' pk=bill.bill_id %}"><button type="button" class="js-accept-bill accept-btn"><i class="fa fa-check"></i> Accepter</button></a>
            <button type="button"  class="js-reject-bill reject-btn"><i class="fa fa-times-circle"></i> Rejeter</button>
            <button type="button"  data-url="{% url 'bill_update' pk=bill.bill_id %}" class="js-update-bill edit-btn"><i class="fa fa-plus"></i> Ajouter OV</button>
        </div>
        {% endif %}
        {% if bill.decision_FC == "2" and bill.transfer_order == '' %}
        <div class="actions pull-right">
            <button type="button"  data-url="{% url 'bill_update' pk=bill.bill_id %}" class="js-update-bill edit-btn"><i class="fa fa-plus"></i> Ajouter OV</button>
        </div>
        {% endif %}
    </div>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-bill">
        <div class="modal-dialog">
          <div class="modal-content">
          </div>
        </div>
    </div>

    <div class="popup">
        <div class="inner">
          <form method="get" action="{% url 'bill_treatment_FC' pk=bill.bill_id %}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-header">
                <h4 class="modal-title"><strong>Choisir les Motifs de Rejet</strong></h4>
              </div>
              <div class="modal-body" style="padding-bottom: 45px; padding-top: 45px">
                    {% render_field form.rejection_reasonFC class="form-control chosen-select" multiple="multiple" %}
              </div>
              <div class="modal-footer">
                <button type="submit" class="submit-btn">Valider</button>
              </div>
         </form>
        </div>
    </div>


    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>

    <script>
    $(document).ready(function () {
        // Popup
        $(".js-reject-bill").click(function () {
           $(".popup").fadeIn(200);
           $("#id_rejection_reasonFC").chosen();

        });

        $(".popup").click(function () {
           $(this).fadeOut(200);
        });

        $(".popup .inner").click(function (e) {
           e.stopPropagation();
        });

        $(".popup .close").click(function (e) {
            e.preventDefault();
           $(".popup").fadeOut(200);
        });

    });

    var loadForm = function () {
    var btn = $(this);
    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-bill").modal("show");
      },
      success: function (data) {
        $("#modal-bill .modal-content").html(data.html_form);
      }
    });
    };
    var saveForm = function () {
    var form = $(this),
        id = $(".js-bill-update-form").data("id");
        if (window.location.hostname === "127.0.0.1"){
            redirect_url = "http://" + window.location.hostname + ":8000/bill_consulting_not_treated_FC";
        }else{
            redirect_url = window.location.hostname + ":8000/bill_consulting_not_treated_FC";
        }

    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
            if (form.attr("action").includes("update")){
                window.location = $(".bill-detail").data("id");
            }else{
                window.location = redirect_url;
            }}
        else {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
        }
      },
      error: function (XMLHttpRequest, textStatus, errorThrown) {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
      }
    });
    return false;
    };


    //Update Bill
    $(".actions").on("click", ".js-update-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-update-form", saveForm);

    //Delete Bill
    $(".actions").on("click", ".js-delete-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-delete-form", saveForm);

    </script>
{% endblock %}