InternShipProject/urls.py
from django.contrib import admin
from django.urls import path, re_path, reverse_lazy
from billingManager import views, models, reporting
from django.views.generic import UpdateView, DeleteView, ListView, DetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create_service/', views.create_service, name='create_service'),
    path('create_district/', views.create_district, name='create_district'),
    path('create_town/', views.create_town, name='create_town'),
    path('create_provider/', views.create_provider, name='create_provider'),
    path('create_bill/', views.create_bill, name='create_bill'),
    path('create_tva/', views.create_tva, name='create_tva'),
    path('create_rr/', views.create_rr, name='create_r_r'),
    #path('add_user/', views.add_user, name='add_user'),
    path('connexion/', views.connexion, name='connexion'),
    path('logout/', views.logout_page, name='logout'),

    # Order Office

    path('bill_consulting_opened', views.view_bill_opened, name='bill_consulting_opened'),

    path('bill_consulting_rejected_BO', views.view_bill_rejected_bo, name='bill_consulting_rejected_BO'),

    path('bill_consulting_closed', views.view_bill_closed, name='bill_consulting_closed'),

    path('bill_detail/<pk>', DetailView.as_view(model=models.Bill, template_name='billDetail.html', ),
         name='bill_detail'),

    path('bill_treatment/<pk>', views.bill_treatment, name='bill_treatment'),

    path('BO_treatment/<pk>', views.bo_treatment, name='BO_treatment'),

    path('slip_edit', views.slip_edit, name='slip_edit'),

    path('reporting_BO/<pk>', views.reporting_pdf, name='reporting_BO'),

    # Treating Service

    path('bill_consulting_not_treated_ST', views.view_bill_not_treated_st, name='bill_consulting_not_treated_ST'),

    path('bill_consulting_opened_ST', views.view_bill_opened_st, name='bill_consulting_opened_ST'),

    path('bill_consulting_closed_ST', views.view_bill_closed_st, name='bill_consulting_closed_ST'),


    path('bill_treatment_ST/<pk>', views.bill_treatment_st, name='bill_treatment_ST'),

    path('ST_treatment/<pk>', views.st_treatment, name='ST_treatment'),

    #####

# Financial Service

    path('bill_consulting_not_treated_FC', views.view_bill_not_treated_fc, name='bill_consulting_not_treated_FC'),

    path('bill_consulting_opened_FC', views.view_bill_opened_fc, name='bill_consulting_opened_FC'),

    path('bill_consulting_closed_FC', views.view_bill_closed_fc, name='bill_consulting_closed_FC'),

    path('bill_treatment_FC/<pk>', views.bill_treatment_fc, name='bill_treatment_FC'),

    path('FC_treatment/<pk>', views.fc_treatment, name='FC_treatment'),

    #####

    path('bill/<pk>/delete/', views.bill_delete, name='bill_delete'),

    path('bill/<pk>/update/', views.bill_update, name='bill_update'),

    path('provider_consulting', views.view_provider, name='provider_consulting'),

    path('provider_detail/<pk>', DetailView.as_view(model=models.Provider, template_name='providerDetail.html', ),
         name='provider_detail'),

    path('provider/<pk>/delete/', views.provider_delete, name='provider_delete'),

    path('provider/<pk>/update/', views.provider_update, name='provider_update'),

    path('service_consulting', views.view_service, name='service_consulting'),

    path('service/<pk>/delete/', views.service_delete, name='service_delete'),

    path('service/<pk>/update/', views.service_update, name='service_update'),

    path('town_consulting', views.view_town, name='town_consulting'),

    path('town/<pk>/delete/', views.town_delete, name='town_delete'),

    path('town/<pk>/update/', views.town_update, name='town_update'),

    path('district_consulting', ListView.as_view(model=models.District, template_name='districtConsulting.html', ),
         name='district_consulting'),

    path('district/<pk>/delete/', views.district_delete, name='district_delete'),

    path('district/<pk>/update/', views.district_update, name='district_update'),

    path('tva_consulting', views.view_tva, name='tva_consulting'),

    path('tva/<pk>/delete/', views.tva_delete, name='tva_delete'),

    path('tva/<pk>/update/', views.tva_update, name='tva_update'),

    path('district_consulting', views.view_district, name='district_consulting'),

    path('reasons_consulting', views.view_reason, name='reasons_consulting'),

    path('reason/<pk>/delete/', views.reason_delete, name='reason_delete'),

    path('reason/<pk>/update/', views.reason_update, name='reason_update'),

# Staff

    path('bill_consulting_all', views.view_all_bill, name='bill_consulting_all'),


]

billingManager/models.py

from django.db import models
from django.contrib.auth.models import User


class Service(models.Model):
    service_id = models.AutoField(primary_key=True)
    service_name = models.CharField(max_length=50, verbose_name="Designation du service")
    service_abv = models.CharField(max_length=10, verbose_name='Abreviation du service')

    def __str__(self):
        return self.service_name


class District(models.Model):
    district_id = models.AutoField(primary_key=True)
    district_designation = models.CharField(max_length=50, verbose_name="Designation du district")

    def __str__(self):
        return self.district_designation


class TVA(models.Model):
    tva_id = models.AutoField(primary_key=True)
    tva_rate = models.FloatField(verbose_name="Taux de TVA")

    def __str__(self):
        return str(self.tva_rate)


class Slip(models.Model):
    slip_id = models.AutoField(primary_key=True, verbose_name="Id du bordereau")
    slip_num = models.IntegerField(verbose_name='Numéro du bordereau')
    closed = models.BooleanField(default=False)
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service"
                                , blank=True, null=True)

    def __str__(self):
        return str(self.slip_num) + "/" + str(self.service.service_abv)


class ServiceSlip(models.Model):
    slip_id = models.AutoField(primary_key=True, verbose_name="Id du bordereau")
    slip_num = models.IntegerField(verbose_name='Numéro du bordereau')
    closed = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=1, verbose_name='Valide')

    def __str__(self):
        if self.is_valid:
            returned_val = str(self.slip_num) + "/" + 'Validation'
        else:
            returned_val = str(self.slip_num) + "/" + 'Rejet'
        return returned_val


class RejectionReason(models.Model):
    rejection_id = models.AutoField(primary_key=True)
    reason = models.CharField(max_length=100, verbose_name="Motif de rejet")

    def __str__(self):
        return self.reason


class Town(models.Model):
    town_id = models.AutoField(primary_key=True)
    town_name = models.CharField(max_length=30, verbose_name="Nom de la ville")
    postal_code = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Code postal")

    def __str__(self):
        return self.town_name


class Provider(models.Model):
    GENDER = [
        ('1', 'Madame'),
        ('2', 'Monsieur'),
        ('3', 'Mademoiselle'),
    ]

    provider_id = models.AutoField(primary_key=True)
    gender = models.CharField(max_length=1, choices=GENDER, default='2', verbose_name="Genre")
    provider_last_name = models.CharField(max_length=50, verbose_name="Nom")
    provider_first_name = models.CharField(max_length=50, verbose_name="Prénom")
    provider_address = models.CharField(max_length=150, verbose_name="Addrese")
    town = models.ForeignKey(Town, on_delete=models.PROTECT, verbose_name="Ville")
    email = models.EmailField()
    fixed_phone = models.CharField(max_length=9, verbose_name="Téléphone fix")
    mobile_phone = models.CharField(max_length=10, verbose_name="Téléphone mobile")
    rib = models.CharField(max_length=20, verbose_name="RIB")
    nif = models.CharField(max_length=20, verbose_name="NIF")
    r_commerce = models.CharField(max_length=20, verbose_name="raison Comercial")

    def __str__(self):
        return self.provider_last_name.upper() + " " + self.provider_first_name.capitalize()


class Bill(models.Model):
    DECISION = [
        ('1', 'Non Traiter'),
        ('2', 'Accepter'),
        ('3', 'Refuser'),
    ]

    bill_id = models.AutoField(primary_key=True)
    bill_num = models.CharField(max_length=50, verbose_name="Numéro de facture")
    entry_date = models.DateField(auto_now=True)
    object = models.TextField(max_length=150, verbose_name="Objet")
    bill_type = models.CharField(max_length=100, verbose_name="Type de facture", blank=True)
    decision_ST = models.CharField(max_length=1, choices=DECISION, default='1')
    decision_BO = models.CharField(max_length=1, choices=DECISION, default='1')
    penalty_rate = models.FloatField(default=0, verbose_name="taux de pénalité")
    ht_amount = models.FloatField(verbose_name='Montant HT')
    other_coasts = models.FloatField(default=0, verbose_name="Autres frais")
    decision_FC = models.CharField(max_length=1, choices=DECISION, default='1')
    transfer_order = models.CharField(max_length=20, blank=True, verbose_name="Ordre de virement")
    billing_date = models.DateField(verbose_name="Date de facturation")
    provider = models.ForeignKey(Provider, on_delete=models.PROTECT, verbose_name="Fournisseur")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service")
    district = models.ForeignKey(District, on_delete=models.PROTECT, verbose_name="District")
    tva = models.ForeignKey(TVA, on_delete=models.PROTECT, verbose_name="Taux de TVA")
    slip = models.ForeignKey(Slip, on_delete=models.PROTECT, null=True, verbose_name="Numéro du bordereau")
    service_slip = models.ForeignKey(ServiceSlip, on_delete=models.PROTECT, null=True, verbose_name="Numéro du bordereau de service traitant")
    rejection_reasonBO = models.ManyToManyField(RejectionReason, related_name='motif1')
    rejection_reasonST = models.ManyToManyField(RejectionReason, related_name='motif2')
    rejection_reasonFC = models.ManyToManyField(RejectionReason, related_name='motif3')
    entered_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name='Saisie par')

    def __str__(self):
        return self.bill_num

    class Meta:
        ordering = ('-entry_date',)


class UserProfile(models.Model):
    user_auth = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    mobile_phone = models.CharField(max_length=9, blank=True, verbose_name='Téléphone portable')
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Service", null=True)
    service_all = models.BooleanField(default=False)
    district = models.ForeignKey(District, on_delete=models.PROTECT, verbose_name="District", null=True)
    district_all = models.BooleanField(default=False)
    born_date = models.DateField(verbose_name="Date de naissance", blank=True)
    years_seniority = models.IntegerField(verbose_name="Années d'ancienneté", blank=True)

    def __str__(self):
        return self.user_auth.last_name.upper() + " " + self.user_auth.first_name.capitalize()



billingManager/forms.py
from django.contrib.auth import authenticate
from billingManager import models
from django import forms
from .models import Bill, Provider, Service, Town, District, TVA, RejectionReason


class BillForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = (
            'bill_num', 'provider', 'object', 'bill_type', 'penalty_rate', 'ht_amount', 'other_coasts', 'billing_date',
            'service', 'district', 'tva', 'transfer_order')


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = (
            'gender', 'provider_last_name', 'provider_first_name', 'provider_address', 'town', 'email', 'fixed_phone',
            'mobile_phone', 'rib', 'nif', 'r_commerce')


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = (
            'service_name', 'service_abv')


class TownForm(forms.ModelForm):
    class Meta:
        model = Town
        fields = (
            'town_name', 'postal_code')


class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = (
            'district_designation',)


class TVAForm(forms.ModelForm):
    class Meta:
        model = TVA
        fields = (
            'tva_rate',)


class ReasonForm(forms.ModelForm):
    class Meta:
        model = RejectionReason
        fields = (
            'reason',)


class FormCreateBill(forms.ModelForm):
    class Meta:
        model = models.Bill
        exclude = ('decision_ST', 'decision_FC', 'entry_date', 'rejection_reasonFC', 'slip', 'service_slip',
                   'rejection_reasonST', 'transfer_order', 'rejection_reasonBO', 'decision_BO', 'entered_by')


class FormCreateTown(forms.ModelForm):
    class Meta:
        model = models.Town
        fields = '__all__'


class FormCreateProvider(forms.ModelForm):
    class Meta:
        model = models.Provider
        fields = '__all__'


class FormCreateSlip(forms.ModelForm):
    class Meta:
        model = models.Slip
        fields = '__all__'


class FormCreateService(forms.ModelForm):
    class Meta:
        model = models.Service
        fields = '__all__'


class FormCreateDistrict(forms.ModelForm):
    class Meta:
        model = models.District
        fields = '__all__'


class FormCreateTVA(forms.ModelForm):
    class Meta:
        model = models.TVA
        fields = '__all__'


class FormCreateRejectionReason(forms.ModelForm):
    class Meta:
        model = models.RejectionReason
        fields = '__all__'


class FormAddUser(forms.Form):
    last_name = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50)
    login = forms.CharField(max_length=50, label="Nom d'utilisateur")
    email = forms.EmailField(label="Email")
    born_date = forms.DateField(widget=forms.DateInput)
    mobile_phone = forms.CharField(max_length=9)
    years_seniority = forms.IntegerField()
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
    password_bis = forms.CharField(label="Validation du mot de passe", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(FormAddUser, self).clean()
        password = cleaned_data.get('password')
        password_bis = self.cleaned_data.get('password_bis')
        if password and password_bis and password != password_bis:
            raise forms.ValidationError("Passwords are not identical.")
        return cleaned_data


class FormConnection(forms.Form):
    username = forms.CharField(max_length=50, label="Nom d'utilisateur")
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(FormConnection, self).clean()

        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Wrong login or password")
        return cleaned_data


class FormSlipEdit(forms.ModelForm):
    class Meta:
        model = models.Slip
        fields = ('service',)


class FormBillTreatment(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonBO', )


class FormBillTreatmentST(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonST', )


class FormBillTreatmentFC(forms.ModelForm):
    class Meta:
        model = models.Bill
        fields = ('rejection_reasonFC', )

billingManager/templates/billConsulting.html
{% extends 'baseForm.html' %}
{% load static %}
{% load widget_tweaks %}
{% load poll_extras %}

{% block TitleHTML %}
Consultation des Factures
{% endblock %}

{% block the_form %}
<div class="alert top alert-success" role="alert">
    Operation effectué avec succès !
</div>
<div class="alert top alert-danger" role="alert">
    Operation a échoué car elle est lié à une autre entité !
</div>
<h2>Consultation des Factures</h2>
{% if bill_filters.count != 0 %}
<div class="direct-content">
    <div class="filter-section">
        <form method="get">
           {% csrf_token %}
            <div class="row">
                <div class="col-xs-12 col-md-2" style="padding-left: 0">
                    {% render_field filter.form.bill_num class="form-control" placeholder="Numéro" %}
                </div>
                <div class="col-xs-12 col-md-2">
                    {% render_field filter.form.provider class="form-control" %}
                </div>
                <div class="col-xs-12 col-md-3">
                    {% render_field filter.form.service class="form-control" %}
                </div>
                <div class="col-xs-12 col-md-2">
                    {% render_field filter.form.decision_FC class="form-control" placeholder="Numéro" %}
                </div>
                <div class="col-xs-12 col-md-2">
                    {% render_field filter.form.slip class="form-control" placeholder="Numéro" %}
                </div>
                <div class="col-xs-12 col-md-1">
                    <button type="submit" class="filter-btn">Filter</button>
                </div>
            </div>
        </form>
    </div>
    <table class="table table-hover table-striped table-bordered" id="bill-table">
      <thead>
        <tr>
          <th scope="col">#Numero</th>
          <th scope="col">#Fournisseur</th>
          <th scope="col">#Date</th>
          <th scope="col">#M.Totale</th>
          <th scope="col">#Service</th>
          <th scope="col">#M.Totale</th>
          <th scope="col">#Status</th>
          <th scope="col">#Action</th>
        </tr>
      </thead>
      <tbody>
        {% include 'includes/partial_bill_list.html' %}
      </tbody>
    </table>
    {% include "pagination.html" with page=bill_filters %}
</div>
{% else %}
<div class="direct-content">
    <div class="alert alert-info" role="alert">
        Aucune facture disponible !
    </div>
</div>
{% endif %}
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-bill">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>

    <script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
    <script>
    $('#id_provider option:first').text('Par fournisseur');
    $('#id_service option:first').text('Par service');
    $('#id_decision_FC option:first').text('Par decision FC');
    $('#id_slip option:first').text('Par bordereau');
    $(function () {

    /* Functions */

    var loadForm = function () {
    var btn = $(this);
    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-bill").modal("show");
      },
      success: function (data) {
        $("#modal-bill .modal-content").html(data.html_form);
      }
    });
    };

    var saveForm = function () {
    var form = $(this),
        id = $(".js-bill-update-form").data("id");
    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
          $("#bill-table tbody").html(data.html_bill_list);
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-success").slideDown(300).delay(2500).slideUp(300);
        }
        else {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
        }
      },
      error: function (XMLHttpRequest, textStatus, errorThrown) {
          $("#modal-bill").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
     }
    });
    return false;
    };


    //Update Bill
    $("#bill-table").on("click", ".js-update-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-update-form", saveForm);

    //Delete Bill
    $("#bill-table").on("click", ".js-delete-bill", loadForm);
    $("#modal-bill").on("submit", ".js-bill-delete-form", saveForm);



     
     $("tr").find("td").click(function(){
         if (!($(this).hasClass("not-allowed"))){
            window.location = $(this).parent("tr").data('url');
         }
     });

    });
    </script>
{% endblock %}

billingManager/templates/deleteConfirmation.html
{% extends 'baseForm.html'   %}

{% block TitleHTML %}
    Confirmation de la supression facture
{% endblock %}


{% block the_form %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
    <a href="{% url 'bill_consulting' %}">Annuler</a>
{% endblock %}

billingManager/templates/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Salam</h2>
    <div class="alert alert-success" role="alert">
      Operation effectué avec succès !
    </div>
    <div class="alert alert-danger" role="alert">
      Operation est echouée !
    </div>
</body>
</html>

billingManager/templates/providerConsulting.html
{% extends 'baseForm.html' %}
{% load widget_tweaks %}
{% load static %}
{% block TitleHTML %}
    Consultation des fournisseurs
{% endblock %}

{% block the_form %}

<div class="alert top alert-success" role="alert">
  Operation effectué avec succès !
</div>
<div class="alert top alert-danger" role="alert">
    Operation a échoué car il est lié à une autre entité !
</div>
{% load django_bootstrap_breadcrumbs %}
<div class="row">
    <div class="col-xs-6">
    <h2>Consultation des Fournisseurs</h2>
    </div>
    <div class="col-xs-6">
        {% block content %}
            {{ block.super }}
            {% breadcrumb "Consulter" "provider_consulting" %}
            {% breadcrumb "Fournisseurs" "#" %}
        {% endblock %}
    </div>
</div>
{% if filter.qs.count != 0 %}
<div class="direct-content">
    <div class="filter-section">
        <form method="get">
           {% csrf_token %}
            <div class="row">
                <div class="col-xs-12 col-md-3" style="padding-left: 0">
                    {% render_field filter.form.provider_last_name class="form-control" placeholder="Nom du fournisseur" %}
                </div>
                <div class="col-xs-12 col-md-2">
                    {% render_field filter.form.town class="form-control" %}
                </div>
                <div class="col-xs-12 col-md-2 pull-right">
                    <button type="submit" class="filter-btn">Filter</button>
                </div>
            </div>
        </form>
    </div>
    <table class="table table-hover table-striped table-bordered" id="provider-table">
      <thead>
        <tr>
          <th scope="col">#Nom et Pénom</th>
          <th scope="col">#Adresse</th>
          <th scope="col">#Ville</th>
          <th scope="col">#Num fix</th>
          <th scope="col">#Num tél</th>
          <th scope="col">#RIB</th>
          <th scope="col">#NIF</th>
          <th scope="col" width="10%">#Action</th>
        </tr>
      </thead>
      <tbody>
        {% include 'includes/partial_provider_list.html' %}
      </tbody>
    </table>
        <a href="{% url "create_provider" %}"><button class="submit-btn"><i class="fa fa-plus"></i> Ajouter</button></a>
        {% include "pagination.html" with page=provider_filters %}
</div>
{% else %}
<div class="direct-content">
    <div class="alert alert-info" role="alert">
        Aucun fournisseur disponible !
    </div>
    <a href="{% url "create_provider" %}"><button class="submit-btn"><i class="fa fa-plus"></i> Ajouter</button></a>
</div>
{% endif %}
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-provider">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>
<script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
<script>
$('#id_town option:first').text('Par ville');
$(function () {

  /* Functions */

  var loadForm = function () {
    var btn = $(this);
    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-provider").modal("show");
      },
      success: function (data) {
        $("#modal-provider .modal-content").html(data.html_form);
      }
    });
  };

  var saveForm = function () {
    var form = $(this);
    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
          $("#provider-table tbody").html(data.html_provider_list);
          $("#modal-provider").modal("hide").delay(1000);
          $(".alert-success").slideDown(300).delay(2500).slideUp(300);
        }
        else {
          $("#modal-provider .modal-content").html(data.html_form);
          console.log("hello");
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
        }
      },
      error: function (XMLHttpRequest, textStatus, errorThrown) {
          $("#modal-provider").modal("hide").delay(1000);
          $(".alert-danger").slideDown(300).delay(2500).slideUp(300);
     }
    });
    return false;
  };


  /* Binding */

    //Update Provider
    $("#provider-table").on("click", ".js-update-provider", loadForm);
    $("#modal-provider").on("submit", ".js-provider-update-form", saveForm);

    // Delete Provider
    $("#provider-table").on("click", ".js-delete-provider", loadForm);
    $("#modal-provider").on("submit", ".js-provider-delete-form", saveForm);


});
</script>
{% endblock %}

billingManager/templates/slipEdit.html
{% extends 'baseForm.html'   %}
{% load poll_extras %}
{% load static %}
{% load widget_tweaks %}
{% block TitleHTML %}
    Edition du bordereau
{% endblock %}


{% block the_form %}
{% load django_bootstrap_breadcrumbs %}
<div class="row">
    <div class="col-xs-6">
    <h2>Edition du bordereau</h2>
    </div>
    <div class="col-xs-6">
        {% block content %}
            {{ block.super }}
            {% breadcrumb "Edition" "slip_edit" %}
            {% breadcrumb "Bordereau" "#" %}
        {% endblock %}
    </div>
</div>
<div class="direct-content">
    <div class="filter-section">
        <form method="get">
           {% csrf_token %}
            <div class="row">
                <div class="col-xs-12 col-md-4" style="padding-left: 0">
                    {% render_field form.service class="form-control" placeholder="Service" %}
                </div>
                <div class="col-xs-12 col-md-2">
                    <button type="submit" class="filter-btn">Afficher</button>
                </div>
                <div class="col-xs-12 col-md-2 pull-right">
                    <a href="{% url 'reporting_BO' pk=slip_id %}"><button type="button" class="print-btn"><i class="fa fa-print"></i> Bordereau</button></a>
                </div>
            </div>
        </form>
    </div>
    {% if bills.count == 0 or bills.count is None %}
    <div class="alert alert-info" role="alert">
        Aucune Facture disponible !
    </div>
    {% else %}
    <table class="table table-hover table-striped table-bordered" id="provider-table">
      <thead>
        <tr>
          <th scope="col">Numero</th>
          <th scope="col">Fournisseur</th>
          <th scope="col">Service</th>
          <th scope="col">District</th>
          <th scope="col">Date saisie</th>
          <th scope="col">Montant HT</th>
        </tr>
      </thead>
      <tbody>
        {% include 'includes/partial_bill_service_slip_opened.html' %}
      </tbody>
    </table>
    {% include "pagination.html" with page=bills %}
    {% endif %}
</div>
<script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
<script>
$('#id_service option:first').text('Choisir un service..');
</script>

{% endblock %}